// packages/vue-components/src/components/Charts/ChannelsChart.vue
<script setup lang="ts">
import { tokens } from "@adsmagic/tokens";

interface ChannelData {
  name: string;
  value: number;
  color: string;
}

interface Props {
  data: ChannelData[];
}

const props = withDefaults(defineProps<Props>(), {
  data: () => []
});
</script>

<template>
  <div class="card-shadow flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-6">
    <div class="flex items-start justify-between">
      <div>
        <h2 class="text-lg font-semibold text-slate-900">Canais</h2>
        <p class="text-xs text-slate-500">Performance por canal</p>
      </div>
      <span class="summary-card-badge summary-card-badge--positive">+12,5%</span>
    </div>
    <div class="flex flex-1 flex-col items-center justify-center">
      <!-- Placeholder para gráfico de barras - seria implementado com uma lib Vue -->
      <div class="flex h-48 w-full items-center justify-center rounded-lg bg-slate-50 text-slate-400">
        <div class="text-center">
          <div class="text-2xl font-semibold text-slate-900">Gráfico de Barras</div>
          <div class="text-sm">Canais de comunicação</div>
        </div>
      </div>
      <div class="mt-4 flex w-full justify-between text-xs text-slate-500">
        <span>WhatsApp</span>
        <span>Instagram</span>
        <span>Facebook</span>
        <span>Site</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.summary-card-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: v-bind('tokens.radii.full');
  font-size: v-bind('tokens.typography.sizeXS');
  font-weight: v-bind('tokens.typography.weightMedium');
  padding-inline: v-bind('tokens.spacing.sm');
  padding-block: v-bind('tokens.spacing["2xs"]');
  color: v-bind('tokens.colors.success600');
  background-color: v-bind('tokens.colors.success100');
}
</style>

// apps/dashboard-react/src/components/ChannelsChart.tsx
import React from 'react';

interface ChannelData {
  name: string;
  percentage: number;
  color: string;
}

interface ChannelsChartProps {
  data: ChannelData[];
}

export const ChannelsChart: React.FC<ChannelsChartProps> = ({ data }) => (
  <div className="card-shadow rounded-3xl border border-slate-200 bg-white p-6">
    <div className="flex items-start justify-between">
      <div>
        <h2 className="text-lg font-semibold text-slate-900">Vendas por canal</h2>
        <p className="text-xs text-slate-500">Distribuição de vendas por canal.</p>
      </div>
      <span className="badge-soft">Total de vendas R$</span>
    </div>
    <div className="flex items-center gap-8">
      {/* Donut Chart */}
      <div className="flex-shrink-0">
        <svg viewBox="0 0 200 200" style={{ height: '180px', width: '180px' }}>
          {data.map((channel, index) => {
            const circumference = 2 * Math.PI * 70;
            let offset = 0;
            for (let i = 0; i < index; i++) {
              offset += (data[i].percentage / 100) * circumference;
            }
            const strokeDasharray = (channel.percentage / 100) * circumference;
            return (
              <circle
                key={channel.name}
                cx="100"
                cy="100"
                r="70"
                fill="none"
                stroke={channel.color}
                strokeWidth="20"
                strokeDasharray={strokeDasharray}
                strokeDashoffset={-offset}
              />
            );
          })}
        </svg>
      </div>
      {/* Legend */}
      <div className="flex flex-col gap-2 text-xs">
        {data.map((channel) => (
          <div key={channel.name} className="flex items-center gap-2">
            <div
              className="h-2 w-2 rounded-full"
              style={{ backgroundColor: channel.color, flexShrink: 0 }}
            ></div>
            <span className="text-slate-600">{channel.name}</span>
            <span className="ml-auto font-semibold text-slate-900">{channel.percentage}%</span>
          </div>
        ))}
      </div>
    </div>
  </div>
);
