// packages/vue-components/src/components/Drawer/Drawer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { tokens } from '@adsmagic/tokens';

type DrawerVariant = 'default' | 'overlay';
type DrawerSize = 'sm' | 'md' | 'lg';

const props = withDefaults(
  defineProps<{
    variant?: DrawerVariant;
    size?: DrawerSize;
    isOpen?: boolean;
  }>(),
  {
    variant: 'default',
    size: 'md',
    isOpen: false,
  },
);

const emit = defineEmits<{
  close: [];
}>();

const variantTokens: Record<DrawerVariant, Record<string, string>> = {
  default: {
    backgroundColor: tokens.colors.white,
    border: `1px solid ${tokens.aliases.borderSoft}`,
    boxShadow: tokens.shadows.card,
  },
  overlay: {
    backgroundColor: tokens.colors.white,
    boxShadow: tokens.shadows.pop,
  },
};

const sizeTokens: Record<DrawerSize, Record<string, string>> = {
  sm: {
    width: '300px',
  },
  md: {
    width: '400px',
  },
  lg: {
    width: '500px',
  },
};

const baseStyle = {
  position: 'fixed',
  top: '0',
  right: '0',
  height: '100vh',
  zIndex: '1000',
  display: 'flex',
  flexDirection: 'column',
  fontFamily: tokens.typography.familySans,
  transition: `transform ${tokens.transitions.base}`,
};

const drawerStyle = computed(() => ({
  ...baseStyle,
  ...sizeTokens[props.size],
  ...variantTokens[props.variant],
  transform: props.isOpen ? 'translateX(0)' : 'translateX(100%)',
}));

const overlayStyle = {
  position: 'fixed',
  top: '0',
  left: '0',
  width: '100vw',
  height: '100vh',
  backgroundColor: 'rgba(0, 0, 0, 0.5)',
  zIndex: '999',
};
</script>

<template>
  <Teleport to="body">
    <div v-if="isOpen && variant === 'overlay'" :style="overlayStyle" @click="$emit('close')" />
    <div v-if="isOpen" :style="drawerStyle">
      <slot />
    </div>
  </Teleport>
</template>

// packages/react-components/src/components/Drawer/Drawer.tsx
import { tokens } from "@adsmagic/tokens";
import type {
  CSSProperties,
  ForwardedRef,
  HTMLAttributes,
  ReactNode,
} from "react";
import { forwardRef } from "react";

type DrawerVariant = "default" | "overlay";
type DrawerSize = "sm" | "md" | "lg";

export interface DrawerProps extends HTMLAttributes<HTMLDivElement> {
  variant?: DrawerVariant;
  size?: DrawerSize;
  isOpen?: boolean;
  onClose?: () => void;
  children?: ReactNode;
}

const variantTokens: Record<DrawerVariant, CSSProperties> = {
  default: {
    backgroundColor: tokens.colors.white,
    border: `1px solid ${tokens.aliases.borderSoft}`,
    boxShadow: tokens.shadows.card,
  },
  overlay: {
    backgroundColor: tokens.colors.white,
    boxShadow: tokens.shadows.pop,
  },
};

const sizeTokens: Record<DrawerSize, CSSProperties> = {
  sm: {
    width: "300px",
  },
  md: {
    width: "400px",
  },
  lg: {
    width: "500px",
  },
};

const baseStyle: CSSProperties = {
  position: "fixed",
  top: 0,
  right: 0,
  height: "100vh",
  zIndex: 1000,
  display: "flex",
  flexDirection: "column",
  fontFamily: tokens.typography.familySans,
  transition: `transform ${tokens.transitions.base}`,
};

function DrawerInner(
  {
    children,
    variant = "default",
    size = "md",
    isOpen = false,
    onClose,
    style,
    ...rest
  }: DrawerProps,
  ref: ForwardedRef<HTMLDivElement>,
) {
  const composedStyle: CSSProperties = {
    ...baseStyle,
    ...sizeTokens[size],
    ...variantTokens[variant],
    transform: isOpen ? "translateX(0)" : "translateX(100%)",
    ...style,
  };

  return (
    <>
      {isOpen && variant === "overlay" && (
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            backgroundColor: "rgba(0, 0, 0, 0.5)",
            zIndex: 999,
          }}
          onClick={onClose}
        />
      )}
      {isOpen && (
        <div ref={ref} style={composedStyle} {...rest}>
          {children}
        </div>
      )}
    </>
  );
}

export const Drawer = forwardRef(DrawerInner);
Drawer.displayName = "Drawer";
